### ISSUE TITLE
global vars

### ISSUE THREAD

**Issue by w00d** [Gannicus91/test_project#6]
Использование глобальных переменные без какой-либо на то необходимости.
```python
class ApacheLogListView(generic.ListView):
    model = ApacheLog
    paginate_by = 50
    queryset = QUERY

    def get_queryset(self):
        global QUERY
```

**Comment by Gannicus91** [comment]
с помощью глобальной переменной QUERY можно парсить файл xlsx с учетом фильтров из поискового запроса
в views.download:
`rows = QUERY.values_list('pk', 'ip', 'date', 'tz', 'method', 'referer', 'status', 'resp_size')`

**Comment by w00d** [comment]
так делать нельзя. это совершенно незаконно. наказание за такое преступление - вплоть до расстрела.
